#!/usr/bin/env ruby

# Install

# Copy this script to /etc/munin/plugins/passenger
# chmod 755 /etc/munin/plugins/passenger

# Then add this to /etc/munin/plugin-conf.d/munin-node

# [passenger]
# user root
# command /root/.rbenv/shims/ruby %c
# env.passenger_status /root/.rbenv/shims/passenger-status
# env.passenger_memory_stats /root/.rbenv/shims/passenger-memory-stats
# env.graph_category Passenger
# env.PASSENGER_INSTANCE_REGISTRY_DIR /tmp/aptmp

# And /etc/init.d/munin-node restart

class SimplePassengerStatus
    def cli argv
        if argv[0] == 'config'
            config
        else
            run
        end
    end

    def config
        puts <<-CONFIG
graph_category Passenger
graph_title Passenger stats
graph_vlabel count
graph_args --base 1000 -l 0
graph_info Passenger stats

max_pool_size.label max pool size
app_groups.label app groups
processes.label processes
requests_in_top_level_queue.label requests in top level queue 
requests_in_queue.label requests in queue
sessions.label sessions
processed.label processed /10000
cpu.label %cpu /10
memory.label memory /100
CONFIG

        exit 0
    end

    def str_list str
        str
            .split(/\n/)
            .map(&:strip)
            .reject(&:empty?)
    end

    def run
        status = `passenger-status --no-header`

        str_list("
            Max pool size
            App groups
            Processes
            Requests in top-level queue        
            Requests in queue
            Sessions
            Processed /10000
            CPU /10
            Memory /100
        ").each do |str|
            divisor = 1
            if str =~ /^(.*?)\s*\/\s*(\d+)\s*$/
                str = $1
                divisor = $2.to_f
            end
            key = str.downcase.gsub(/(\s|-)+/, '_')

            total = 0
            status.scan(/#{str}\s*:\s*(\d+)/).flatten.each { |count| 
                total += count.to_i 
            }

            puts "#{key}.value #{total/divisor}"
        end
    end
end

SimplePassengerStatus.new.cli ARGV
